encoder_type: GRU
decoder_type: GRU
encoder_params:
  input_size: 11
  hidden_size: 128
  num_layers: 2
  bidirectional: true
decoder_params:
  input_size: 267
  hidden_size: 128
  num_layers: 2
  bidirectional: true
decoder_use_all_hidden: true
teacher_forcing_ratio: 0.5
learning_rate: 0.001
optimizer_params: {}
lr_scheduler: null
lr_scheduler_params: {}
